# Bonito CTC-CRF RNN Model

[model]
package = "bonito.aed_tf"

[labels]
labels = [ "N", "A", "C", "G", "T" ]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 512
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0
num_layers=6
dropout=0.1
normalize_before = true

[decoder]
d_model = 512
nhead = 8
layers = 3
dropout = 0.1
lb_sm = 0.01
normalize_before = true

[search]
beam_size = 4
max_decode_ratio=0.8
min_decode_ratio=0.0
len_norm=true
dec_layer_num = 3
ths_path = "/workspace/FasterTransformer/build/lib/libpyt_fastertransformer.so"
hid_dim = 512
head_num = 8


[global_norm]
state_len = 5

