# Bonito CTC-CRF RNN Model

[model]
package = "bonito.conformer_trans"

[labels]
labels = [ "N", "A", "C", "G", "T" ]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 768
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0
num_layers=6
dropout=0.1

[pred_net]
emb_dim = 768
hid_dim = 768
layers=1
dropout=0.1

[joint]
hid_dim=768
dropout=0.1

[global_norm]
state_len = 5
