# Bonito CTC-CRF RNN Model

[model]
package = "bonito.conformer_ctc_v2"

[labels]
labels = [ "N", "A", "C", "G", "T" ]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 768
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0
num_layers=6
dropout=0.1
att_out_dim=128

[global_norm]
state_len = 5
