# Bonito CTC-CRF RNN Model

[model]
package = "bonito.transformer"

[labels]
labels = [ "N", "A", "C", "G", "T" ]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 512 
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0
num_layers=6

[global_norm]
state_len = 5

[lr_scheduler]
package = "bonito.schedule"
symbol = "hg_lr_with_warmup_decay"
warmup_ratio = 0.05
